<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html>
    <head>
        <title>This is a very nice hello world</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body>

        <p> Hello <?php echo '' ?> </p>

        <table>
            <tr>
                <td>Tutorial</td>
                <td><a href="http://www.magentocommerce.com/knowledge-base/entry/magento-for-dev-part-4-magento-layouts-blocks-and-templates">http://www.magentocommerce.com/knowledge-base/entry/magento-for-dev-part-4-magento-layouts-blocks-and-templates</a></td>
            </tr>

            <tr>
                <td>This file</td>
                <td><?php echo __FILE__ ?></td>
            </tr>

            <tr>
                <td>Related file</td>
                <td>app/design/frontend/base/default/layout/helloworld.xml</td>
            </tr>

            <tr>
                <td>Related file</td>
                <td>app/code/local/TinyApps/HelloWorld/layout/helloworld.xml</td>
            </tr>
        </table>
    </body>
</html>
