<h1>Hello <?php echo $this->getName() ?></h1>
<h2>Very nice to meet you!</h2>


<table>
    <tr>
        <td>Tutorial</td>
        <td>
            <a href="http://www.excellencemagentoblog.com/magento-part5-series-model-blocks-layours">
                http://www.excellencemagentoblog.com/magento-part5-series-model-blocks-layours
            </a>
        </td>
    </tr>

    <tr>
        <td>This file:</td>
        <td><?php echo __FILE__ ?></td>
    </tr>

    <tr>
        <td>Related file</td>
        <td>app/design/frontend/base/default/layout/helloworld.xml</td>
    </tr>

    <tr>
        <td>Related file</td>
        <td>app/code/local/TinyApps/HelloWorld/layout/helloworld.xml</td>
    </tr>
</table>